Repository Bastion-BaaS/admin-frontend, pull requests merged in 2022-03, with the labels that each got.

#2 Front end redux
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/actions/BastionActions.js
  src/actions/CloudCodeActions.js
  src/actions/CollectionActions.js
  src/actions/FileActions.js
  src/actions/UserActions.js
  src/components/AddUserForm.js
  src/components/BaasMain.js
  src/components/BaasModels.js
  src/components/BastionHome.js
  src/components/BastionLayout.js
  src/components/BastionSidebar.js
  src/components/CloudCode.js
  src/components/CollectionSummary.js
  src/components/Collections.js
  src/components/CreateBaaS.js
  src/components/Files.js
  src/components/Home.js
  src/components/LinkHome.js
  src/components/Sidebar.js
  src/components/SidebarBast.js
  src/components/SidebarBastionLink.js
  src/components/SidebarHome.js
  src/components/SidebarItems.js
  src/components/TopBar.js
  src/components/Users.js
  src/lib/Store.js
  src/lib/apiClient.js
  src/reducers/bastions.js
  src/reducers/cloudCode.js
  src/reducers/collections.js
  src/reducers/db_models.js
  src/reducers/files.js
  src/reducers/users.js
Labels: Ready to Merge

#3 Add baseUrl and Icons
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  src/lib/apiClient.js
Labels: Needs Review

#4 Improve styling add colors and font
  package.json
  src/App.css
  src/App.js
  src/actions/CollectionActions.js
  src/assets/images/bastion_logo_dark.png
  src/assets/images/bw_logo.svg
  src/components/AddUserForm.js
  src/components/BastionHome.js
  src/components/BastionLayout.js
  src/components/BastionSidebar.js
  src/components/Card.js
  src/components/CloudCode.js
  src/components/CloudCodeCard.js
  src/components/Collection.js
  src/components/CollectionSummary.js
  src/components/Collections.js
  src/components/File.js
  src/components/Files.js
  src/components/Home.js
  src/components/LinkHome.js
  src/components/Overview.js
  src/components/SidebarBastionLink.js
  src/components/SidebarHome.js
  src/components/SidebarItems.js
  src/components/User.js
  src/components/Users.js
  src/lib/apiClient.js
  src/reducers/collections.js
  tailwind.config.js
Labels: Reviewing
